# Generated by Django 5.0.1 on 2024-01-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_client_user_alter_settings_time'),
        ('users', '0003_remove_user_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.ManyToManyField(to='main.client', verbose_name='Клиенты'),
        ),
    ]
