# Generated by Django 5.0.1 on 2024-01-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_client_massage_massage_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='client',
            name='sur_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
        migrations.RemoveField(
            model_name='massage',
            name='client',
        ),
        migrations.AddField(
            model_name='massage',
            name='client',
            field=models.ManyToManyField(to='main.client', verbose_name='Клиенты'),
        ),
    ]
