# Generated by Django 5.0.1 on 2024-01-18 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('sur_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('mail', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime', models.DateTimeField(auto_now=True, verbose_name='Время и дата последней попытки')),
                ('status', models.CharField(choices=[('start', 'Запущена'), ('finish', 'Завершена'), ('created', 'Создана')], default='created', max_length=10, verbose_name='Статус')),
                ('response', models.CharField(max_length=100, verbose_name='Ответ сервера')),
            ],
            options={
                'verbose_name': 'Логи',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=150, verbose_name='Тема письма')),
                ('body', models.TextField(verbose_name='Тело письма')),
                ('logs', models.ManyToManyField(blank=True, null=True, to='main.logs', verbose_name='Логи')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2024, 1, 18, 23, 25, 1, 692051), verbose_name='Время рассылки')),
                ('frequency', models.CharField(choices=[('once_a_day', 'Раз в день'), ('once_a_week', 'Раз в неделю'), ('once_a_month', 'Раз в месяц')], default='Раз в день', verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('start', 'Запущена'), ('finish', 'Завершена'), ('created', 'Создана')], default='created', max_length=10, verbose_name='Статус')),
                ('client', models.ManyToManyField(to='main.client', verbose_name='Клиенты')),
                ('massage', models.ManyToManyField(to='main.massage', verbose_name='Письма')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
