# Generated by Django 5.0.1 on 2024-01-14 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'verbose_name': 'Логи', 'verbose_name_plural': 'Логи'},
        ),
        migrations.AddField(
            model_name='client',
            name='massage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.massage', verbose_name='Сообщениe'),
        ),
        migrations.AddField(
            model_name='massage',
            name='logs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.logs', verbose_name='Логи'),
        ),
        migrations.AddField(
            model_name='massage',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.settings', verbose_name='Настройки'),
        ),
    ]
