# Generated by Django 5.0.1 on 2024-01-20 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 20, 19, 50, 27, 39340), verbose_name='Время рассылки'),
        ),
    ]
