# Generated by Django 5.0.1 on 2024-01-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_logs_status_alter_settings_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='status',
            field=models.CharField(choices=[('start', 'Запущена'), ('finish', 'Завершена'), ('created', 'Создана')], default='Запущена', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='frequency',
            field=models.CharField(choices=[('once_a_day', 'Раз в день'), ('once_a_week', 'Раз в неделю'), ('once_a_month', 'Раз в месяц')], default='Раз в день', verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='status',
            field=models.CharField(choices=[('start', 'Запущена'), ('finish', 'Завершена'), ('created', 'Создана')], default='Запущена', max_length=10, verbose_name='Статус'),
        ),
    ]
