# Generated by Django 5.0.1 on 2024-01-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_logs_options_client_massage_massage_logs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='frequency',
            field=models.CharField(choices=[('Раз в день', 'Раз в день'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], default='Раз в день', verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='status',
            field=models.CharField(choices=[('Завершена', 'Завершена'), ('Создана', 'Создана'), ('Запущена', 'Запущена')], default='Создана', max_length=10, verbose_name='Статус'),
        ),
    ]
