# Generated by Django 5.0.1 on 2024-01-16 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_settings_frequency_alter_settings_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='massage',
        ),
        migrations.AddField(
            model_name='massage',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='Клиенты'),
        ),
    ]
