# Generated by Django 5.0.1 on 2024-01-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_logs_status_alter_settings_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='client',
            field=models.ManyToManyField(to='main.client', verbose_name='Клиенты'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='status',
            field=models.CharField(choices=[('start', 'Запущена'), ('finish', 'Завершена'), ('created', 'Создана')], default='Создана', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='status',
            field=models.CharField(choices=[('start', 'Запущена'), ('finish', 'Завершена'), ('created', 'Создана')], default='Создана', max_length=10, verbose_name='Статус'),
        ),
    ]
