# Generated by Django 5.0.1 on 2024-01-17 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_logs_status_alter_settings_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massage',
            name='client',
        ),
        migrations.RemoveField(
            model_name='massage',
            name='logs',
        ),
        migrations.RemoveField(
            model_name='massage',
            name='settings',
        ),
        migrations.AddField(
            model_name='settings',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.massage', verbose_name='Письмо'),
        ),
    ]
