# Generated by Django 5.0.1 on 2024-01-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_massage_client_remove_massage_logs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='message',
            new_name='massage',
        ),
    ]
