# Generated by Django 5.0.1 on 2024-01-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_message_settings_massage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='massage',
        ),
        migrations.AddField(
            model_name='settings',
            name='massage',
            field=models.ManyToManyField(to='main.massage', verbose_name='Письма'),
        ),
    ]
