# Generated by Django 4.2.7 on 2024-01-21 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_massage_user_settings_user_alter_settings_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 17, 7, 6, 639292), verbose_name='Время рассылки'),
        ),
    ]
