# Generated by Django 5.0.1 on 2024-01-18 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_settings_massage_settings_massage'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='logs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.logs', verbose_name='Логи'),
        ),
    ]
