# Generated by Django 4.2.7 on 2024-01-21 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_settings_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 17, 49, 32, 280285), verbose_name='Время рассылки'),
        ),
    ]
